"""empty message

Revision ID: 5104b96ac3b9
Revises: 9c3fe1a0bdaf
Create Date: 2017-08-05 08:35:46.291554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5104b96ac3b9'
down_revision = '9c3fe1a0bdaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_blog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'blog', ['comment_blog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'comment_blog_id')
    # ### end Alembic commands ###
