"""empty message

Revision ID: 9c3fe1a0bdaf
Revises: d21dd4535092
Create Date: 2017-08-04 08:25:42.598725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3fe1a0bdaf'
down_revision = 'd21dd4535092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('author_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'author_id')
    # ### end Alembic commands ###
